-- MySQL Script generated by MySQL Workbench
-- Tue Sep  6 13:30:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejercicio_relaciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejercicio_relaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ejercicio_relaciones` ;
USE `ejercicio_relaciones` ;

-- -----------------------------------------------------
-- Table `ejercicio_relaciones`.`COHORTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejercicio_relaciones`.`COHORTE` (
  `cohorte12_id` INT NOT NULL,
  `alumnos_id` INT NOT NULL,
  `instructor_id` INT NOT NULL,
  `numero_alumnos` INT NOT NULL,
  `horario` VARCHAR(255) NOT NULL,
  `tipo_sesiones` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cohorte12_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejercicio_relaciones`.`ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejercicio_relaciones`.`ALUMNO` (
  `alumno_id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `edad` INT NOT NULL,
  `curp` VARCHAR(255) NOT NULL,
  `rfc` VARCHAR(255) NULL,
  `nivel_ingles` VARCHAR(255) NOT NULL,
  `amonestaciones` INT NOT NULL,
  PRIMARY KEY (`alumno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejercicio_relaciones`.`INSTRUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejercicio_relaciones`.`INSTRUCTOR` (
  `instructor_id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `edad` INT NOT NULL,
  `cumpleanios` DATE NOT NULL,
  `rfc` VARCHAR(255) NOT NULL,
  `supervisor` VARCHAR(255) NOT NULL,
  `sesiones` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`instructor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejercicio_relaciones`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejercicio_relaciones`.`EQUIPO` (
  `equipo_id` INT NOT NULL,
  `alumno_id` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `cantidad_integrantes` INT NOT NULL,
  `logo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`equipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ejercicio_relaciones`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ejercicio_relaciones`.`DIRECCION` (
  `direccion_id` INT NOT NULL,
  `alumno_id` INT NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `cp` INT NOT NULL,
  PRIMARY KEY (`direccion_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
