-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 13:31:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`PROFESOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`PROFESOR` (
  `id_prof` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prof`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`ALUMNO` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(25) NOT NULL,
  `PROFESOR_id` INT NOT NULL,
  PRIMARY KEY (`id_alumno`),
  INDEX `fk_ALUMNO_PROFESOR_idx` (`PROFESOR_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_PROFESOR`
    FOREIGN KEY (`PROFESOR_id`)
    REFERENCES `escuela`.`PROFESOR` (`id_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`MATERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`MATERIA` (
  `codigo_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `grado` INT NOT NULL,
  PRIMARY KEY (`codigo_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`ALUMNO_has_MATERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`ALUMNO_has_MATERIA` (
  `ALUMNO_id_alumno` INT NOT NULL,
  `MATERIA_codigo_materia` INT NOT NULL,
  PRIMARY KEY (`ALUMNO_id_alumno`, `MATERIA_codigo_materia`),
  INDEX `fk_ALUMNO_has_MATERIA_MATERIA1_idx` (`MATERIA_codigo_materia` ASC) VISIBLE,
  INDEX `fk_ALUMNO_has_MATERIA_ALUMNO1_idx` (`ALUMNO_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_has_MATERIA_ALUMNO1`
    FOREIGN KEY (`ALUMNO_id_alumno`)
    REFERENCES `escuela`.`ALUMNO` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNO_has_MATERIA_MATERIA1`
    FOREIGN KEY (`MATERIA_codigo_materia`)
    REFERENCES `escuela`.`MATERIA` (`codigo_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
